title: "Grey Key Studios Blog"
description: "A blog documenting cybersecurity, game dev, music, and creative tech projects."
locale: en-US
url: "https://blog.greykeystudios.com"
baseurl: ""  # empty for root of subdomain
logo: "/assets/images/color.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

# Theme
remote_theme: "mmistakes/so-simple-theme"
skin: "/assets/css/skins/default.css"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Markdown & Permalinks
markdown: kramdown
permalink: /:categories/:title/

# Author
author:
  name: "Grey Key Studios"
  picture: /assets/images/color.png
  links:
    - title: "GitHub"
      url: "https://github.com/GreyKeyStudios"
      icon: fab fa-github
    - title: "Main Site"
      url: "https://greykeystudios.com"
      icon: fas fa-link

# Footer
footer_links:
  - title: "Feed"
    url: atom.xml
    icon: fas fa-rss-square

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
