# Site Info
title: "Grey Key Studios Blog"
description: "A blog documenting cybersecurity, game dev, music, and creative tech projects."
url: "https://blog.greykeystudios.com"
baseurl: ""  # leave empty for root on custom domain
repository: "GreyKeyStudios/Blog"
logo: "/assets/images/color.png"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"  # Options: default, air, dark, contrast, neon, etc.

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Build settings
include: ["_pages"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor"]

# Navigation structure (optional but good practice)
collections:
  posts:
    output: true

# Markdown & Permalink
markdown: kramdown
permalink: /:categories/:title/

# Defaults for layout and author info
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Author
author:
  name: "Grey Key Studios"
  avatar: "/assets/images/color.png"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/GreyKeyStudios"
    - label: "Main Site"
      icon: "fas fa-link"
      url: "https://greykeystudios.com"

# Enable search box
search: true

# Theme features (optional enhancement)
theme_settings:
  header:
    title: true
