# Site settings
title: "Grey Key Studios Blog"
description: "A blog documenting my cybersecurity and creative tech projects."
locale: en-US
url: "https://blog.greykeystudios.com"
baseurl: ""  # keep empty for root of subdomain
logo: "/assets/images/logo.png"  # update path once you upload your logo
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

# Theme
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Analytics and Comments (optional)
google_analytics: ""  # Add ID if needed
disqus:
  shortname: ""        # Add Disqus shortname if used

# Social (optional)
twitter:
  username: "GreyKeyStudios"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
permalink: /:categories/:title/
feed:
  path: atom.xml

# Pagination
paginate: 5
paginate_path: /page:num/

# Search
search_full_content: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Author Info
author:
  name: Grey Key Studios
  picture: /assets/images/logo.png  # Use your logo or personal avatar
  email: ""
  twitter: "GreyKeyStudios"
  links:
    - title: "GitHub"
      url: "https://github.com/GreyKeyStudios"
      icon: "fab fa-github"
    - title: "Main Site"
      url: "https://greykeystudios.com"
      icon: "fas fa-link"

# Footer Links
footer_links:
  - title: "Feed"
    url: atom.xml
    icon: fas fa-rss-square

# Defaults for posts
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
exclude:
  - README.md
#logo image
favicon: /assets/images/logo.png
